"""Added Methods and Relationships

Revision ID: 3b64594f01a9
Revises: e1f9e4e100b7
Create Date: 2023-09-04 15:41:49.916266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b64594f01a9'
down_revision: Union[str, None] = 'e1f9e4e100b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
